# Generated by Django 5.1.5 on 2025-02-26 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0003_course_degree_degreecourse_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingwebsiteapp.degree')),
                ('user_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
