# Generated by Django 5.1.1 on 2025-03-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0005_simplemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='degree_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='is_major',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
