# Generated by Django 5.1.1 on 2025-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0006_degree_degree_number_degree_is_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='is_major',
        ),
        migrations.AddField(
            model_name='degree',
            name='degree_type',
            field=models.IntegerField(choices=[(1, 'Major'), (2, 'Minor'), (3, 'Certificate')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
