# Generated by Django 5.1.1 on 2025-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0007_remove_degree_is_major_degree_degree_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='degree_type',
        ),
        migrations.AddField(
            model_name='degree',
            name='type',
            field=models.IntegerField(choices=[(1, 'Major'), (2, 'Minor'), (3, 'Certificate')], default=1),
            preserve_default=False,
        ),
    ]
