# Generated by Django 5.1.1 on 2025-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0008_remove_degree_degree_type_degree_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='type',
            new_name='degree_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
