# Generated by Django 5.1.1 on 2025-03-16 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0009_rename_type_degree_degree_type_alter_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='advisingwebsiteapp.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_by_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisingwebsiteapp.chatmember'),
        ),
        migrations.DeleteModel(
            name='SimpleMessage',
        ),
    ]
