# Generated by Django 5.1.1 on 2025-04-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingwebsiteapp', '0010_alter_chatmember_user_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='corequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recent_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degreecourse',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='advisingwebsiteapp.chat'),
        ),
    ]
